---
# tasks file for verify

- name: Verify fabric underlay.
  block:

    - name: Get OSPF neighbors.
      cisco.nxos.nxos_command:
        commands:
          - show ip ospf neighbors
      register: verify_ospf_neighbors

    - name: Print info about OSPF.
      ansible.builtin.debug:
        msg: Spines should be neighbor with all leafs and border-leafs.
        verbosity: 0
      run_once: true

    - name: Print OSPF Neighbors.
      ansible.builtin.debug:
        msg:
          - show ip ospf neighbors
          - "{{ verify_ospf_neighbors['stdout_lines'][0] }}"
        verbosity: 0

    - name: Get PIM neighbors.
      cisco.nxos.nxos_command:
        commands:
          - show ip pim neighbor
      register: verify_pim_neighbors

    - name: Print info about PIM.
      ansible.builtin.debug:
        msg: Spines should be neighbor with all leafs and border-leafs.
        verbosity: 0
      run_once: true

    - name: Print PIM Neighbors.
      ansible.builtin.debug:
        msg:
          - show ip pim neighbor
          - "{{ verify_pim_neighbors['stdout_lines'][0] }}"
        verbosity: 0


- name: Verify fabric overlay.
  block:

    - name: Get NVE Peers.
      cisco.nxos.nxos_command:
        commands:
          - show nve peers
      register: verify_nve_peers
      when: network_role is ansible.builtin.search('leaf')

    - name: Print info about NVE peers.
      ansible.builtin.debug:
        msg: You will not see any peers before hosts-traffic has been initiated between peers.
        verbosity: 0
      run_once: true
      when: network_role is ansible.builtin.search('leaf')

    - name: Print NVE Peers.
      ansible.builtin.debug:
        msg:
          - show nve peers
          - "{{ verify_nve_peers['stdout_lines'][0] }}"
        verbosity: 0
      when: network_role is ansible.builtin.search('leaf')


    - name: Get EVPN BGP neigbors.
      cisco.nxos.nxos_command:
        commands:
          - show bgp l2vpn evpn summary
      register: verify_bgp_neighbors

    - name: Print info about EVPN BGP neighbors.
      ansible.builtin.debug:
        msg:
          - Spine (RR) should see all leafs and border-leafs as neighbors.
          - Border-leafs should also see remote border-leafs in separate BGP AS as neighbors.
        verbosity: 0
      run_once: true

    - name: Print EVPN BGP neighbors.
      ansible.builtin.debug:
        msg:
          - show bgp l2vpn evpn summary
          - "{{ verify_bgp_neighbors['stdout_lines'][0] }}"
        verbosity: 0


- name: Verify the VXLAN configuration.
  when: network_role is ansible.builtin.search('leaf')
  block:

    - name: Run VXLAN config-check.
      cisco.nxos.nxos_command:
        commands:
          - show consistency-checker vxlan config-check
      register: verify_config_check
      vars:
        ansible_command_timeout: 60

    - name: Print VXLAN config-check.
      ansible.builtin.debug:
        msg:
          - show consistency-checker vxlan config-check
          - "{{ verify_config_check['stdout_lines'][0] }}"
        verbosity: 0


- name: Verify DCI encryption.
  when: network_role is eq('border-leaf')
  block:

    - name: Get MKA summary information.
      cisco.nxos.nxos_command:
        commands:
          - show macsec mka summary
      register: verify_macsec_mka_summary

    - name: Print info about macsec.
      ansible.builtin.debug:
        msg: DCI interfaces should have status Secured.
        verbosity: 0
      run_once: true

    - name: Print macsec mka summary.
      ansible.builtin.debug:
        msg:
          - show macsec mka summary
          - "{{ verify_macsec_mka_summary['stdout_lines'][0] }}"
        verbosity: 0
